# 캡스톤 프로젝트를 위한 Docker Compose 파일(포트번호: 5433)
services:
  db:
    image: postgres:16
    container_name: capstone-med-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: tap
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: med_management_db
    volumes:
      - ./docker-config/data:/var/lib/postgresql/data