/*
 유저 테이블 
- account_type 컬럼에서 확장성을 위해 BOOLEAN 대신 SMALLINT 채택 및 CHECK 제약조건 추가. 
 */
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY
	,login_id VARCHAR(50) NOT NULL
	,password VARCHAR(255) NOT NULL
	,name VARCHAR(50) NOT NULL 
	,email VARCHAR(100) NOT NULL 
	,birth_date DATE NOT NULL
	,account_type SMALLINT NOT NULL               -- 역할 구분: 0(PATIENT), 1(GUARDIAN)
	,created_at TIMESTAMP DEFAULT NOW() NOT NULL 
	,updated_at TIMESTAMP DEFAULT NOW() NOT NULL
	,deleted_at TIMESTAMP                      -- NULL이면 활성화 상태 
	,CONSTRAINT pk_user_id PRIMARY KEY (user_id)
	,CONSTRAINT uq_login_id UNIQUE (login_id)
	,CONSTRAINT uq_user_email UNIQUE (email)
	,CONSTRAINT ck_account_type CHECK (account_type IN(0,1))
);
/*
 사용자-하드웨어 매핑 테이블
 - 앱에서 기기 등록 시 매핑됨.
 - 하드웨어가 보내는 device_code를 통해 어느 사용자의 기기인지 식별.
*/
CREATE TABLE hardwares (
    hardware_id INTEGER GENERATED BY DEFAULT AS IDENTITY
    ,user_id INTEGER NOT NULL
    ,device_code VARCHAR(50) NOT NULL             -- ESP32 기기 고유 번호 등
    ,registered_at TIMESTAMP DEFAULT NOW() NOT NULL
    ,updated_at TIMESTAMP DEFAULT NOW() NOT NULL    -- 기기 정보(별명 등) 수정 시
    ,deleted_at TIMESTAMP                           -- 기기 연결 해제 시 
    ,CONSTRAINT pk_hardware_id PRIMARY KEY (hardware_id)
    ,CONSTRAINT fk_hardware_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
    ,CONSTRAINT uq_hardware_device_code UNIQUE (device_code)
);
/*
NFC 스티커 테이블 
- 실시간으로 어떤 스케줄에 어떤 스티커가 매핑되어 있는지 관리. 
- 새 스티커를 쓰면 nfc_uid만 업데이트. 
- 복약 스케줄과 1:N 관계로 복약 스케줄이 삭제되면 자동 삭제됨.
*/
CREATE TABLE tag_mappings (
    mapping_id INTEGER GENERATED BY DEFAULT AS IDENTITY   
    ,user_id INTEGER NOT NULL
    ,tag_uid VARCHAR(50) NOT NULL               
    ,created_at TIMESTAMP DEFAULT NOW() NOT NULL 
    ,last_tagged_at TIMESTAMP      
    ,deleted_at TIMESTAMP
    ,CONSTRAINT pk_mapping_id PRIMARY KEY (mapping_id)
    ,CONSTRAINT fk_mapping_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
	,CONSTRAINT uq_mapping_tag_uid UNIQUE (tag_uid)
 );
/*
복약 스케줄 테이블
- 사용자가 설정한 '알림'이나'계획'.
- 스티커를 버려도 스케줄 기록은 남음. 
 */
CREATE TABLE medication_schedule (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY
	,mapping_id INTEGER NOT NULL
	,schedule_name VARCHAR(100) NOT NULL
	,take_time TIME NOT NULL
	,days_of_week SMALLINT NOT NULL
	,calibrated_weight DECIMAL(5,2) 
	,created_at TIMESTAMP DEFAULT NOW() NOT NULL 
	,updated_at TIMESTAMP DEFAULT NOW() NOT NULL
	,deleted_at TIMESTAMP 
	,CONSTRAINT pk_schedule_id PRIMARY KEY (schedule_id) 
	,CONSTRAINT fk_schedule_mapping_id FOREIGN KEY (mapping_id) REFERENCES tag_mappings (mapping_id) ON DELETE CASCADE
	,CONSTRAINT ck_days_range CHECK (days_of_week BETWEEN 0 AND 127)
);
/*
복약 로그 테이블
- 하드웨어 센서의 측정값과 복약 성공 여부 기록.
- 부모 스케줄이 삭제(Soft Delete)되어도 기록을 보존.
- status 컬럼에서 확장성을 위해 BOOLEAN 대신 SMALLINT 채택 및 CHECK 제약조건 추가. 
*/
CREATE TABLE medication_logs(
	log_id INTEGER GENERATED BY DEFAULT AS IDENTITY
	,mapping_id INTEGER NOT NULL
	,schedule_id INTEGER NOT NULL
	,user_id INTEGER NOT NULL
	,scheduled_time TIME NOT NULL 
	,take_time TIMESTAMP DEFAULT NOW() NOT NULL
	,measured_weight DECIMAL(5,2) NOT NULL
	,status SMALLINT NOT NULL                      -- 0(FAIL), 1(AUTO_SUCCESS), 2(MANUAL_CONFIRMED)
	,created_at TIMESTAMP DEFAULT NOW() NOT NULL 
	,updated_at TIMESTAMP DEFAULT NOW() NOT NULL
	,CONSTRAINT pk_log_id PRIMARY KEY (log_id)
	,CONSTRAINT fk_log_mapping_id FOREIGN KEY (mapping_id) REFERENCES tag_mappings (mapping_id) ON DELETE CASCADE
	,CONSTRAINT fk_log_schedule_id FOREIGN KEY (schedule_id) REFERENCES medication_schedule (schedule_id) ON DELETE CASCADE
	,CONSTRAINT fk_log_user_id FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE 
	,CONSTRAINT ck_status_range CHECK (status IN(0,1,2))
);